### ISSUE TITLE
Ask SSR feature

### ISSUE THREAD

**Issue by hendivalon** [justdlabs/inertia.ts#30]
Hello Bang Irsyad,

Thank you for the package. i _nubitol_ here :)

Is the SSR run properly?

I just cloned the fresh codes and run test-ssr , yes no error found in each page.
But seems not printed like SSR when check the page source.

I'm not really familiar with ssr-csr differences.
Please your comment.

<img width="1317" alt="Screenshot 2023-06-26 at 22 30 26" src="https://github.com/irsyadadl/inertia.ts/assets/54342125/b20d2599-2575-4c86-8c10-e1ab0cb03ee8">

**Comment by irsyadadl** [comment]
I need to upgrade it. Just wait a second.

**Comment by irsyadadl** [comment]
This is has been fixed with [4b9d7e6](https://github.com/irsyadadl/inertia.ts/commit/4b9d7e6c45466c9f9d9652a9cc452d2dde1bd9ec).

**Comment by irsyadadl** [comment]
This is has been fixed with [4b9d7e6](https://github.com/irsyadadl/inertia.ts/commit/4b9d7e6c45466c9f9d9652a9cc452d2dde1bd9ec).
