### ISSUE TITLE
Blank di browser Handphone

### ISSUE THREAD

**Issue by masadi** [justdlabs/inertia.ts#32]
Saya coba pake ini, di browser PC/Laptop normal
Akses di handphone blank
- iPhone 6
- Browser firefox, safari & chrome

**Comment by irsyadadl** [comment]
Apakah masalah sudah dibawa ke production. Karena pada dasarnya inertia yang mendukung ssr, harus di jalankan ssr nya. Dan sudah di pastikan, jika di test dengan **ngrok** tidak akan berhasil. Namun, jika di coba dengan `php artisan serve --host=192.168.1...` harusnya bisa. Pastikan satu jaringan antara phone dan host.

**Comment by masadi** [comment]
saya install di server online
coba om cek di mas-adi.net
