### ISSUE TITLE
STATUS NOT FOUND

### ISSUE THREAD

**Issue by essential-writer-codebase** [justdlabs/inertia.ts#34]
I'm run ssr server on localhost with command:
php artisan inertia:start-ssr

And get error:
![image](https://github.com/irsyadadl/inertia.ts/assets/11135501/c519b954-dd2f-42fb-9ae5-e1ae8f631f64)

And i try:
npm run preview

the result is the same...

**Comment by irsyadadl** [comment]
Just trying to pull this project. And get it up and running very nice. I don't find find something like that. I will open this issue for just 3 days. If anyone can't show the same errors. It will close.  Please try to check everything you've done to be correct.
