### ISSUE TITLE
Change Baseurl

### ISSUE THREAD

**Issue by yuxxeun** [justdlabs/inertia.ts#79]
**_How to change base url?_**

I've read the description on the readme and have replaced the base url with `APP_URL=http://localhost:8000` ,
but everything's on navigation still redirect to `http://inertia.test`

![image](https://github.com/user-attachments/assets/47a253ff-b2c3-46f0-9d6d-102caef7f760)

**Comment by irsyadadl** [comment]
Actually, the navigation it self not depend to `.env` file. Can you explain more ?

**Comment by yuxxeun** [comment]
yes, now it's solved.
maybe because of  `cache` (?), but last night I tried deleting it via artisan, but it still didn't work, I also restarted the server, and run it again but it still didn't change.
after I restarted the device, it just worked haha.
